pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'image-service:latest'
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/suprkar/microCommerce.git'
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE ./image-service/'
            }
        }
        stage('Test') {
            steps {
                // Define steps for running your tests here
                sh 'echo "Running tests in Image Service"'
            }
        }
        stage('Deploy') {
            steps {
                sh 'kubectl apply -f ./image-service/k8s/deployment.yaml'
                sh 'kubectl apply -f ./image-service/k8s/service.yaml'
            }
        }
    }
}
