apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
      - name: image-service
        image: pes2ug21cs556supratikkar/cloudcomputing-6:image-service
        ports:
        - containerPort: 4003

---
apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  type: ClusterIP
  ports:
  - port: 4003
    targetPort: 4003
  selector:
    app: image-service
